<a href="https://colab.research.google.com/github/Priyanka4872/Python-Repo01/blob/main/multi_indexing_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a=np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
a[1:,::-1]

array([[ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20]])

In [ ]:
a[4:,0::2]

array([[20, 22, 24]])

In [ ]:
a[::4,::4]

array([[ 0,  4],
       [20, 24]])